#!/bin/bash
#
# Checks if message for ..: Permission denied

command="    .."

# clean up
stop_shell
rm -f $tmp_file

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
echo "$SHELL: 1: ..: Permission denied" > file_to_check
diff -q $ERROROUTPUTFILE file_to_check
match=$?
if [ $match -eq 0 ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm -f file_to_check
